name: flutter_emoji_mart
description: A flutter package for emoji selection inspired by emoji-mart. Elevate your Flutter app's emoji-picking experience.
version: 1.0.2
homepage: https://github.com/LucasXu0/emoji_mart

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  visibility_detector: ^0.4.0+2
  flutter_sticky_header: ^0.6.5
  sliver_tools: ^0.2.12
  easy_debounce: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.5

flutter:
  assets:
    - assets/emoji_data.json

